# Night Observation Configuration Template with Gmail SMTP
# This file contains default settings for night observation scheduling

# Default observation settings
nights:
  # Number of nights to schedule (integer)
  count: 1
  
  # Default start and end times (ISO format or 'sunset'/'sunrise')
  # Can be overridden by geographic calculations
  start: "sunset"
  end: "sunrise"

# Email notification settings
email:
  # Default recipient for observation reports
  recipient: "hunter@406mt.org"
  
  # Email format preference
  format: "html"  # Options: html, text, json
  
  # SMTP configuration (optional - falls back to system mail if not provided)
  smtp:
    enabled: true
    server: "smtp.gmail.com"
    port: 587
    use_tls: true
    username: "hunter@406mt.org"
    # Password will be set via environment variable GMAIL_APP_PASSWORD
    # or via command line argument
    password: ""

# Geographic location for sunset/sunrise calculations
location:
  # Coordinates in decimal degrees
  latitude: 46.9080
  longitude: -114.0722 
  
  # Optional: timezone (if not specified, will be calculated from coordinates)
  timezone: "America/Denver"
  
  # Elevation in meters (affects twilight calculations)
  elevation: 980

# Alternative: Static time configuration (overrides location-based calculations)
# Uncomment to use fixed times instead of geographic calculations
static_times:
  enabled: false
  start_time: "20:00"  # 24-hour format
  end_time: "06:00"

# Output and logging settings
output:
  # Verbosity level: 0=quiet, 1=normal, 2=verbose, 3=debug
  verbosity: 1
  
  # Log file location (uses rotating file handler)
  # File will rotate at 10MB with 5 backup copies
  log_file: /tmp/fox_report.log
  
  # Enable syslog logging (writes to system log)
  use_syslog: true
  
  # Output format for reports
  format: "table"  # Options: table, json, csv, yaml

# Advanced settings
advanced:
  # Astronomical twilight types for calculations
  twilight_type: "nautical"  # Options: civil, nautical, astronomical
  
  # Buffer time in minutes before/after calculated times
  buffer_minutes: 15
