# Fox Report Configuration Template
# Copy this file to create your own configuration

# Frigate integration settings
frigate:
  # Path to Frigate database file
  database_path: "/home/hunter/frigate/config/frigate.db"
  
  # Frigate web UI base URL (without trailing slash)
  base_url: "https://frig.mso.mt"
  
  # Alternative: if using different ports or local access
  # base_url: "http://192.168.1.100:5000"

# Number of nights to analyze in reports
nights:
  count: 3

# Email notification settings
email:
  # Email recipient
  recipient: "hunter@406mt.org"
  
  # Email format preference
  format: "html"  # Options: html, text
  
  # SMTP configuration for Gmail
  smtp:
    enabled: true
    server: "smtp.gmail.com"
    port: 587
    use_tls: true
    username: "hunter@406mt.org"
    # Password should be set via GMAIL_APP_PASSWORD environment variable

# Geographic location for sunset/sunrise calculations
location:
  # Coordinates in decimal degrees
  latitude: 46.9080
  longitude: -114.0722 
  
  # Timezone (Mountain Time with daylight savings)
  timezone: "America/Denver"
  
  # Elevation in meters (affects twilight calculations)
  elevation: 980

# Output and logging settings
output:
  # Verbosity level: 0=quiet, 1=normal, 2=verbose, 3=debug
  verbosity: 1
  
  # Directory for temporary files and reports
  temp_dir: "/tmp"
  
  # Log file location (uses rotating file handler)
  log_file: "/tmp/fox_report.log"
  
  # Enable syslog logging
  use_syslog: false

# Advanced settings
advanced:
  # Astronomical twilight type for dusk/dawn calculations
  twilight_type: "nautical"  # Options: civil, nautical, astronomical
  
  # Buffer time in minutes before/after calculated times
  buffer_minutes: 15
  
  # Maximum number of events to show per camera in email
  max_events_per_camera: 10
